name: CodeQL Analysis, Security Scans and Deploy to Amazon ECS

on:
  push:
    branches:
      - main

# ----------------------------
# Environment variables for AWS and ECS
# ----------------------------
env:
  AWS_REGION: ap-south-1                   # AWS region
  ECR_REPOSITORY: webapp-hospital          # Amazon ECR repository
  ECS_SERVICE: web-ecs-service             # ECS service name
  ECS_CLUSTER: web-ecs-cluster             # ECS cluster name
  ECS_TASK_DEFINITION: ecs-task-revision36.json # ECS task definition file
  CONTAINER_NAME: web-app                  # ECS container name

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  # ----------------------------
  # Snyk Scan (SCA)
  # ----------------------------
  snyk:
    name: Snyk Scan (SCA)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Monitor project in Snyk dashboard
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

      - name: Run Snyk test and save SARIF report
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --fail-on=all

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  # ----------------------------
  # CodeQL Scan (SAST)
  # ----------------------------
  codeQL:
    name: CodeQL Analysis (SAST)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ] # Node.js language
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # ----------------------------
  # DAST (OWASP ZAP)
  # ----------------------------
  dast:
    name: Dynamic Application Security Testing (DAST)
    runs-on: ubuntu-latest
    needs: [snyk, codeQL]   # Run after Snyk & CodeQL
    services:
      mongodb: # Start MongoDB service for the app
        image: mongo:5.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: hospital_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build the application image
      - name: Build application image
        run: |
          docker build -t webapp-test .

      # Start application container with MongoDB connection
      - name: Start application container
        run: |
          docker run -d \
            --name webapp \
            --network host \
            -e MONGO_URI="mongodb://127.0.0.1:27017/hospital_test" \
            -e NODE_ENV="test" \
            -e PORT="8080" \
            -e HOST="0.0.0.0" \
            webapp-test
          sleep 20

      # Wait until the app is healthy
      - name: Wait for application to be ready
        run: |
          timeout=120
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "App is ready"
              break
            fi
            echo "Waiting... ($elapsed/$timeout)"
            sleep 5
            elapsed=$((elapsed + 5))
          done
          if [ $elapsed -ge $timeout ]; then
            echo "App failed to start"
            docker logs webapp --tail 50
            exit 1
          fi

      # ----------------------------
      # OWASP ZAP Baseline Scan
      # ----------------------------
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:8080"
          # Output SARIF file + HTML/JSON/MD reports
          cmd_options: "-a -j -l INFO -I --output zap-baseline.sarif --format sarif"
        continue-on-error: true

      - name: Upload ZAP Baseline Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-baseline-report
          path: |
            report_html.html
            report_json.json
            report_md.md
            zap-baseline.sarif

      # ----------------------------
      # OWASP ZAP Full Scan
      # ----------------------------
      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: "http://localhost:8080"
          # Output SARIF file + HTML/JSON/MD reports
          cmd_options: "-a -j -I --output zap-full.sarif --format sarif"
        continue-on-error: true

      - name: Upload ZAP Full Scan Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-full-scan-report
          path: |
            report_html.html
            report_json.json
            report_md.md
            zap-full.sarif

      # Upload SARIF results to GitHub Security tab
      - name: Upload ZAP SARIF results (Baseline)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: zap-baseline.sarif

      - name: Upload ZAP SARIF results (Full Scan)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: zap-full.sarif

      # Cleanup containers
      - name: Stop and remove container
        if: always()
        run: |
          docker stop webapp || true
          docker rm webapp || true

  # ----------------------------
  # Deploy to Amazon ECS
  # ----------------------------
  deploy:
    name: Deploy to Amazon ECS
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      issues: write
      security-events: write
    environment: production
    needs: [dast]   # Deploy only if DAST passes

    steps:
      - name: Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: Kulunu98
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to production"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          timeout-minutes: 3       

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.build-image.outputs.image }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
